/**
 * Google ADK Code Generator
 * 
 * Generates valid Python code using google.adk.* imports from the visual flow.
 */

import type { Node, Edge } from '@xyflow/react';

interface ADKAgentData {
  name?: string;
  label?: string;
  model?: string;
  modelProvider?: string;
  instruction?: string;
  description?: string;
  outputKey?: string;
  beforeModelCallback?: boolean;
  afterModelCallback?: boolean;
  beforeToolCallback?: boolean;
  afterToolCallback?: boolean;
  maxIterations?: number;
  // Tool data
  functionName?: string;
  code?: string;
  toolType?: string;
  serverName?: string;
  transport?: string;
  command?: string;
  url?: string;
}

/**
 * Generate ADK Python code from nodes and edges.
 */
export function generateADKCode(nodes: Node[], edges: Edge[]): string {
  if (nodes.length === 0) {
    return '# Add nodes to generate Google ADK code\n';
  }

  const lines: string[] = [];
  const imports = new Set<string>();

  // Collect all node types
  const llmAgents = nodes.filter(n => n.type === 'adk-llm-agent');
  const sequentialAgents = nodes.filter(n => n.type === 'adk-sequential');
  const parallelAgents = nodes.filter(n => n.type === 'adk-parallel');
  const loopAgents = nodes.filter(n => n.type === 'adk-loop');
  const functionTools = nodes.filter(n => n.type === 'adk-function-tool');
  const mcpTools = nodes.filter(n => n.type === 'adk-mcp-tool');
  const builtinTools = nodes.filter(n => n.type === 'adk-builtin-tool');

  // Build imports
  imports.add('import os');

  const agentImports: string[] = [];
  if (llmAgents.length > 0) agentImports.push('LlmAgent');
  if (sequentialAgents.length > 0) agentImports.push('SequentialAgent');
  if (parallelAgents.length > 0) agentImports.push('ParallelAgent');
  if (loopAgents.length > 0) agentImports.push('LoopAgent');

  if (agentImports.length > 0) {
    imports.add(`from google.adk.agents import ${agentImports.join(', ')}`);
  }

  // Model imports (flat module — google.adk.models)
  const modelProviders = new Set(llmAgents.map(a => (a.data as ADKAgentData)?.modelProvider || 'gemini'));
  if (modelProviders.has('gemini') || modelProviders.has(undefined as any)) {
    imports.add('from google.adk.models import Gemini');
  }
  if (modelProviders.has('vertex-ai')) {
    imports.add('from google.adk.models import Gemini');
  }
  if (modelProviders.has('litellm')) {
    imports.add('from google.adk.models import LiteLlm');
  }

  // Tool imports
  if (functionTools.length > 0) {
    imports.add('from google.adk.tools import FunctionTool');
  }
  if (mcpTools.length > 0) {
    imports.add('from google.adk.tools.mcp_tool import MCPToolset, SseConnectionParams, StdioConnectionParams');
  }
  for (const tool of builtinTools) {
    const toolType = (tool.data as ADKAgentData)?.toolType || 'google_search';
    if (toolType !== 'code_execution') {
      imports.add(`from google.adk.tools import ${toolType}`);
    }
  }

  // Runner & session
  imports.add('from google.adk.runners import Runner');
  imports.add('from google.adk.sessions import InMemorySessionService');

  // Callbacks
  const hasCallbacks = llmAgents.some(a => {
    const d = a.data as ADKAgentData;
    return d?.beforeModelCallback || d?.afterModelCallback || d?.beforeToolCallback || d?.afterToolCallback;
  });
  if (hasCallbacks) {
    imports.add('from google.genai import types');
  }

  // Write header
  lines.push('"""');
  lines.push('Generated by AgenticBuilder (Google ADK)');
  lines.push('Framework: Google Agent Development Kit v1.36.x');
  lines.push('"""');
  lines.push('');

  // Write imports
  for (const imp of Array.from(imports).sort()) {
    lines.push(imp);
  }
  lines.push('');
  lines.push('');

  // Generate function tools
  if (functionTools.length > 0) {
    lines.push('# ─── Tools ───────────────────────────────────────────');
    lines.push('');
    for (const tool of functionTools) {
      const d = tool.data as ADKAgentData;
      const fnName = d?.functionName || `tool_${tool.id.replace(/-/g, '_')}`;
      const desc = d?.description || 'A custom tool function.';
      const code = d?.code || '    return {"status": "success"}';

      lines.push(`def ${fnName}(query: str) -> dict:`);
      lines.push(`    """${desc}"""`);
      lines.push(code.startsWith('    ') ? code : `    ${code}`);
      lines.push('');
      lines.push(`${fnName}_tool = FunctionTool(func=${fnName})`);
      lines.push('');
    }
  }

  // Generate MCP tools
  if (mcpTools.length > 0) {
    lines.push('# ─── MCP Toolsets ────────────────────────────────────');
    lines.push('');
    for (const tool of mcpTools) {
      const d = tool.data as ADKAgentData;
      const varName = (d?.serverName || `mcp_${tool.id}`).replace(/[^a-zA-Z0-9_]/g, '_');
      const transport = d?.transport || 'stdio';

      if (transport === 'stdio') {
        lines.push(`${varName}_toolset = MCPToolset(`);
        lines.push(`    connection_params=StdioConnectionParams(`);
        lines.push(`        command="${d?.command || 'npx'}",`);
        lines.push(`        args=["-y", "${d?.serverName || 'my-mcp-server'}"],`);
        lines.push(`    )`);
        lines.push(`)`)
      } else {
        lines.push(`${varName}_toolset = MCPToolset(`);
        lines.push(`    connection_params=SseConnectionParams(`);
        lines.push(`        url="${d?.url || 'http://localhost:3000/sse'}",`);
        lines.push(`    )`);
        lines.push(`)`)
      }
      lines.push('');
    }
  }

  // Generate callbacks if needed
  if (hasCallbacks) {
    lines.push('# ─── Callbacks ───────────────────────────────────────');
    lines.push('');
    lines.push('def before_model_callback(callback_context, llm_request):');
    lines.push('    """Called before each LLM invocation. Return modified request or None."""');
    lines.push('    print(f"[Before Model] Agent: {callback_context.agent_name}")');
    lines.push('    return None  # Return None to proceed, or modified LlmResponse to short-circuit');
    lines.push('');
    lines.push('def after_model_callback(callback_context, llm_response):');
    lines.push('    """Called after each LLM invocation. Return modified response or None."""');
    lines.push('    print(f"[After Model] Agent: {callback_context.agent_name}")');
    lines.push('    return None');
    lines.push('');
    lines.push('def before_tool_callback(callback_context, tool, args):');
    lines.push('    """Called before tool execution. Return dict to skip tool, or None to proceed."""');
    lines.push('    print(f"[Before Tool] {tool.name} with args: {args}")');
    lines.push('    return None');
    lines.push('');
    lines.push('def after_tool_callback(callback_context, tool, args, tool_response):');
    lines.push('    """Called after tool execution. Return modified response or None."""');
    lines.push('    print(f"[After Tool] {tool.name} returned: {tool_response}")');
    lines.push('    return None');
    lines.push('');
  }

  // Generate agents
  lines.push('# ─── Agents ──────────────────────────────────────────');
  lines.push('');

  // Find tool connections for each agent
  const getToolsForAgent = (agentId: string): string[] => {
    const toolNodeIds = edges
      .filter(e => e.target === agentId && e.targetHandle === 'tools')
      .map(e => e.source);

    const toolNames: string[] = [];
    for (const toolNodeId of toolNodeIds) {
      const toolNode = nodes.find(n => n.id === toolNodeId);
      if (!toolNode) continue;

      if (toolNode.type === 'adk-function-tool') {
        const d = toolNode.data as ADKAgentData;
        const fnName = d?.functionName || `tool_${toolNode.id.replace(/-/g, '_')}`;
        toolNames.push(`${fnName}_tool`);
      } else if (toolNode.type === 'adk-mcp-tool') {
        const d = toolNode.data as ADKAgentData;
        const varName = (d?.serverName || `mcp_${toolNode.id}`).replace(/[^a-zA-Z0-9_]/g, '_');
        toolNames.push(`${varName}_toolset`);
      } else if (toolNode.type === 'adk-builtin-tool') {
        const d = toolNode.data as ADKAgentData;
        toolNames.push(d?.toolType || 'google_search');
      }
    }
    return toolNames;
  };

  // Find sub-agents for workflow agents
  const getSubAgents = (agentId: string): string[] => {
    const subAgentIds = edges
      .filter(e => e.target === agentId && e.targetHandle === 'sub-agents')
      .map(e => e.source);

    return subAgentIds
      .map(id => {
        const node = nodes.find(n => n.id === id);
        if (!node) return null;
        const d = node.data as ADKAgentData;
        return d?.name || `agent_${id.replace(/-/g, '_')}`;
      })
      .filter(Boolean) as string[];
  };

  // Generate LLM agents first
  for (const agent of llmAgents) {
    const d = agent.data as ADKAgentData;
    const name = d?.name || `agent_${agent.id.replace(/-/g, '_')}`;
    const model = d?.model || 'gemini-2.0-flash';
    const instruction = d?.instruction || 'You are a helpful assistant.';
    const tools = getToolsForAgent(agent.id);
    const subAgents = getSubAgents(agent.id);

    lines.push(`${name} = LlmAgent(`);
    lines.push(`    name="${name}",`);
    lines.push(`    model=Gemini(model="${model}"),`);
    lines.push(`    instruction="""${instruction}""",`);

    if (d?.description) {
      lines.push(`    description="${d.description}",`);
    }

    if (tools.length > 0) {
      lines.push(`    tools=[${tools.join(', ')}],`);
    }

    if (subAgents.length > 0) {
      lines.push(`    sub_agents=[${subAgents.join(', ')}],`);
    }

    if (d?.outputKey) {
      lines.push(`    output_key="${d.outputKey}",`);
    }

    if (d?.beforeModelCallback) {
      lines.push(`    before_model_callback=before_model_callback,`);
    }
    if (d?.afterModelCallback) {
      lines.push(`    after_model_callback=after_model_callback,`);
    }
    if (d?.beforeToolCallback) {
      lines.push(`    before_tool_callback=before_tool_callback,`);
    }
    if (d?.afterToolCallback) {
      lines.push(`    after_tool_callback=after_tool_callback,`);
    }

    lines.push(`)`)
    lines.push('');
  }

  // Generate workflow agents
  for (const agent of sequentialAgents) {
    const d = agent.data as ADKAgentData;
    const name = d?.name || `sequential_${agent.id.replace(/-/g, '_')}`;
    const subAgents = getSubAgents(agent.id);

    lines.push(`${name} = SequentialAgent(`);
    lines.push(`    name="${name}",`);
    lines.push(`    sub_agents=[${subAgents.join(', ')}],`);
    if (d?.description) {
      lines.push(`    description="${d.description}",`);
    }
    lines.push(`)`)
    lines.push('');
  }

  for (const agent of parallelAgents) {
    const d = agent.data as ADKAgentData;
    const name = d?.name || `parallel_${agent.id.replace(/-/g, '_')}`;
    const subAgents = getSubAgents(agent.id);

    lines.push(`${name} = ParallelAgent(`);
    lines.push(`    name="${name}",`);
    lines.push(`    sub_agents=[${subAgents.join(', ')}],`);
    if (d?.description) {
      lines.push(`    description="${d.description}",`);
    }
    lines.push(`)`)
    lines.push('');
  }

  for (const agent of loopAgents) {
    const d = agent.data as ADKAgentData;
    const name = d?.name || `loop_${agent.id.replace(/-/g, '_')}`;
    const subAgents = getSubAgents(agent.id);

    lines.push(`${name} = LoopAgent(`);
    lines.push(`    name="${name}",`);
    lines.push(`    sub_agents=[${subAgents.join(', ')}],`);
    if (d?.maxIterations) {
      lines.push(`    max_iterations=${d.maxIterations},`);
    }
    if (d?.description) {
      lines.push(`    description="${d.description}",`);
    }
    lines.push(`)`)
    lines.push('');
  }

  // Runner setup
  lines.push('# ─── Runner ──────────────────────────────────────────');
  lines.push('');

  // Find the root agent (the one that isn't a sub-agent of anything)
  const allSubAgentIds = new Set(
    edges.filter(e => e.targetHandle === 'sub-agents').map(e => e.source)
  );
  const rootAgents = [...llmAgents, ...sequentialAgents, ...parallelAgents, ...loopAgents]
    .filter(a => !allSubAgentIds.has(a.id));

  const rootAgent = rootAgents[0];
  const rootName = rootAgent
    ? (rootAgent.data as ADKAgentData)?.name || `agent_${rootAgent.id.replace(/-/g, '_')}`
    : llmAgents[0]
      ? (llmAgents[0].data as ADKAgentData)?.name || 'agent'
      : 'agent';

  lines.push('APP_NAME = "agent_builder_app"');
  lines.push('');
  lines.push('session_service = InMemorySessionService()');
  lines.push('');
  lines.push(`runner = Runner(`);
  lines.push(`    agent=${rootName},`);
  lines.push(`    app_name=APP_NAME,`);
  lines.push(`    session_service=session_service,`);
  lines.push(`)`)
  lines.push('');

  // Main execution
  lines.push('');
  lines.push('# ─── Execute ─────────────────────────────────────────');
  lines.push('');
  lines.push('async def main():');
  lines.push('    """Run the agent with a user message."""');
  lines.push('    session = await session_service.create_session(');
  lines.push('        app_name=APP_NAME,');
  lines.push('        user_id="user-1",');
  lines.push('    )');
  lines.push('');
  lines.push('    response = await runner.run_async(');
  lines.push('        session_id=session.id,');
  lines.push('        user_id="user-1",');
  lines.push('        new_message=types.Content(');
  lines.push('            role="user",');
  lines.push('            parts=[types.Part(text="Hello! What can you help me with?")],');
  lines.push('        ),');
  lines.push('    )');
  lines.push('');
  lines.push('    # Print agent response');
  lines.push('    for event in response:');
  lines.push('        if event.content and event.content.parts:');
  lines.push('            for part in event.content.parts:');
  lines.push('                if part.text:');
  lines.push('                    print(part.text)');
  lines.push('');
  lines.push('');
  lines.push('if __name__ == "__main__":');
  lines.push('    import asyncio');
  lines.push('    asyncio.run(main())');
  lines.push('');

  return lines.join('\n');
}
